/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.macrosoft.seccion.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.macrosoft.seccion.logic.dto.SeccionDTO;
import co.edu.uniandes.csw.macrosoft.seccion.persistence.entity.SeccionEntity;

public abstract class _SeccionConverter {

	public static SeccionDTO entity2PersistenceDTO(SeccionEntity entity){
		if (entity != null) {
			SeccionDTO dto = new SeccionDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setCupoMaximo(entity.getCupoMaximo());
					dto.setSalon(entity.getSalon());
					dto.setInscritos(entity.getInscritos());
					dto.setProfesor_seccionId(entity.getProfesor_seccionId());
			return dto;
		}else{
			return null;
		}
	}
	
	public static SeccionEntity persistenceDTO2Entity(SeccionDTO dto){
		if(dto!=null){
			SeccionEntity entity=new SeccionEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setCupoMaximo(dto.getCupoMaximo());
			
					entity.setSalon(dto.getSalon());
			
					entity.setInscritos(dto.getInscritos());
			
					entity.setProfesor_seccionId(dto.getProfesor_seccionId());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<SeccionDTO> entity2PersistenceDTOList(List<SeccionEntity> entities){
		List<SeccionDTO> dtos=new ArrayList<SeccionDTO>();
		for(SeccionEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<SeccionEntity> persistenceDTO2EntityList(List<SeccionDTO> dtos){
		List<SeccionEntity> entities=new ArrayList<SeccionEntity>();
		for(SeccionDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}