/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.macrosoft.seccion.master.persistence;
import co.edu.uniandes.csw.macrosoft.estudiante.logic.dto.EstudianteDTO;
import co.edu.uniandes.csw.macrosoft.seccion.master.persistence.entity.SeccionenEspera_seccionEntity;
import co.edu.uniandes.csw.macrosoft.estudiante.persistence.converter.EstudianteConverter;
import co.edu.uniandes.csw.macrosoft.estudiante.logic.dto.EstudianteDTO;
import co.edu.uniandes.csw.macrosoft.seccion.master.persistence.entity.Seccioninscritos_seccionEntity;
import co.edu.uniandes.csw.macrosoft.estudiante.persistence.converter.EstudianteConverter;
import co.edu.uniandes.csw.macrosoft.seccion.logic.dto.SeccionDTO;
import co.edu.uniandes.csw.macrosoft.seccion.master.logic.dto.SeccionMasterDTO;
import co.edu.uniandes.csw.macrosoft.seccion.master.persistence.api._ISeccionMasterPersistence;
import co.edu.uniandes.csw.macrosoft.seccion.persistence.api.ISeccionPersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _SeccionMasterPersistence implements _ISeccionMasterPersistence {

  	@PersistenceContext(unitName="ConflictoPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected ISeccionPersistence seccionPersistence;  

    public SeccionMasterDTO getSeccion(Long seccionId) {
        SeccionMasterDTO seccionMasterDTO = new SeccionMasterDTO();
        SeccionDTO seccion = seccionPersistence.getSeccion(seccionId);
        seccionMasterDTO.setSeccionEntity(seccion);
        seccionMasterDTO.setListenEspera_seccion(getSeccionenEspera_seccionEntityList(seccionId));
        seccionMasterDTO.setListinscritos_seccion(getSeccioninscritos_seccionEntityList(seccionId));
        return seccionMasterDTO;
    }

    public SeccionenEspera_seccionEntity createSeccionenEspera_seccionEntity(SeccionenEspera_seccionEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteSeccionenEspera_seccionEntity(Long seccionId, Long enEspera_seccionId) {
        Query q = entityManager.createNamedQuery("SeccionenEspera_seccionEntity.deleteSeccionenEspera_seccionEntity");
        q.setParameter("seccionId", seccionId);
        q.setParameter("enEspera_seccionId", enEspera_seccionId);
        q.executeUpdate();
    }

    public List<EstudianteDTO> getSeccionenEspera_seccionEntityList(Long seccionId) {
        ArrayList<EstudianteDTO> resp = new ArrayList<EstudianteDTO>();
        Query q = entityManager.createNamedQuery("SeccionenEspera_seccionEntity.getByMasterId");
        q.setParameter("seccionId",seccionId);
        List<SeccionenEspera_seccionEntity> qResult =  q.getResultList();
        for (SeccionenEspera_seccionEntity entity : qResult) { 
            if(entity.getEnEspera_seccionIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EstudianteConverter.entity2PersistenceDTO(entity.getEnEspera_seccionIdEntity()));
        }
        return resp;
    }
    public Seccioninscritos_seccionEntity createSeccioninscritos_seccionEntity(Seccioninscritos_seccionEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deleteSeccioninscritos_seccionEntity(Long seccionId, Long inscritos_seccionId) {
        Query q = entityManager.createNamedQuery("Seccioninscritos_seccionEntity.deleteSeccioninscritos_seccionEntity");
        q.setParameter("seccionId", seccionId);
        q.setParameter("inscritos_seccionId", inscritos_seccionId);
        q.executeUpdate();
    }

    public List<EstudianteDTO> getSeccioninscritos_seccionEntityList(Long seccionId) {
        ArrayList<EstudianteDTO> resp = new ArrayList<EstudianteDTO>();
        Query q = entityManager.createNamedQuery("Seccioninscritos_seccionEntity.getByMasterId");
        q.setParameter("seccionId",seccionId);
        List<Seccioninscritos_seccionEntity> qResult =  q.getResultList();
        for (Seccioninscritos_seccionEntity entity : qResult) { 
            if(entity.getInscritos_seccionIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(EstudianteConverter.entity2PersistenceDTO(entity.getInscritos_seccionIdEntity()));
        }
        return resp;
    }

}
