/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.macrosoft.profesor.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.macrosoft.profesor.logic.dto.ProfesorDTO;
import co.edu.uniandes.csw.macrosoft.profesor.persistence.api._IProfesorPersistence;
import co.edu.uniandes.csw.macrosoft.profesor.persistence.converter.ProfesorConverter;
import co.edu.uniandes.csw.macrosoft.profesor.persistence.entity.ProfesorEntity;

public abstract class _ProfesorPersistence implements _IProfesorPersistence {

  	@PersistenceContext(unitName="ConflictoPU")
 
	protected EntityManager entityManager;
	
	public ProfesorDTO createProfesor(ProfesorDTO profesor) {
		ProfesorEntity entity=ProfesorConverter.persistenceDTO2Entity(profesor);
		entityManager.persist(entity);
		return ProfesorConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<ProfesorDTO> getProfesors() {
		Query q = entityManager.createQuery("select u from ProfesorEntity u");
		return ProfesorConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public ProfesorDTO getProfesor(Long id) {
		return ProfesorConverter.entity2PersistenceDTO(entityManager.find(ProfesorEntity.class, id));
	}

	public void deleteProfesor(Long id) {
		ProfesorEntity entity=entityManager.find(ProfesorEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateProfesor(ProfesorDTO detail) {
		ProfesorEntity entity=entityManager.merge(ProfesorConverter.persistenceDTO2Entity(detail));
		ProfesorConverter.entity2PersistenceDTO(entity);
	}

}