/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.macrosoft.profesor.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.macrosoft.profesor.logic.dto.ProfesorDTO;
import co.edu.uniandes.csw.macrosoft.profesor.persistence.entity.ProfesorEntity;

public abstract class _ProfesorConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static ProfesorDTO entity2PersistenceDTO(ProfesorEntity entity){
		if (entity != null) {
			ProfesorDTO dto = new ProfesorDTO();
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setAniosExperiencia(entity.getAniosExperiencia());
					dto.setNumPublicaciones(entity.getNumPublicaciones());
 
			    if(entity.getFechaVinculacion() != null){
					dto.setFechaVinculacion(DATE_FORMAT.format(entity.getFechaVinculacion()));
				}	
			return dto;
		}else{
			return null;
		}
	}
	
	public static ProfesorEntity persistenceDTO2Entity(ProfesorDTO dto){
		if(dto!=null){
			ProfesorEntity entity=new ProfesorEntity();
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setAniosExperiencia(dto.getAniosExperiencia());
			
					entity.setNumPublicaciones(dto.getNumPublicaciones());
			
 
			      try{ 
			        if(dto.getFechaVinculacion() != null){
						entity.setFechaVinculacion(DATE_FORMAT.parse(dto.getFechaVinculacion()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_ProfesorConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ProfesorDTO> entity2PersistenceDTOList(List<ProfesorEntity> entities){
		List<ProfesorDTO> dtos=new ArrayList<ProfesorDTO>();
		for(ProfesorEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ProfesorEntity> persistenceDTO2EntityList(List<ProfesorDTO> dtos){
		List<ProfesorEntity> entities=new ArrayList<ProfesorEntity>();
		for(ProfesorDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}