/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.macrosoft.seccion.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.macrosoft.seccion.logic.dto.SeccionDTO;
import co.edu.uniandes.csw.macrosoft.seccion.persistence.api._ISeccionPersistence;
import co.edu.uniandes.csw.macrosoft.seccion.persistence.converter.SeccionConverter;
import co.edu.uniandes.csw.macrosoft.seccion.persistence.entity.SeccionEntity;

public abstract class _SeccionPersistence implements _ISeccionPersistence {

  	@PersistenceContext(unitName="ConflictoPU")
 
	protected EntityManager entityManager;
	
	public SeccionDTO createSeccion(SeccionDTO seccion) {
		SeccionEntity entity=SeccionConverter.persistenceDTO2Entity(seccion);
		entityManager.persist(entity);
		return SeccionConverter.entity2PersistenceDTO(entity);
	}

	@SuppressWarnings("unchecked")
	public List<SeccionDTO> getSeccions() {
		Query q = entityManager.createQuery("select u from SeccionEntity u");
		return SeccionConverter.entity2PersistenceDTOList(q.getResultList());
	}

	public SeccionDTO getSeccion(Long id) {
		return SeccionConverter.entity2PersistenceDTO(entityManager.find(SeccionEntity.class, id));
	}

	public void deleteSeccion(Long id) {
		SeccionEntity entity=entityManager.find(SeccionEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateSeccion(SeccionDTO detail) {
		SeccionEntity entity=entityManager.merge(SeccionConverter.persistenceDTO2Entity(detail));
		SeccionConverter.entity2PersistenceDTO(entity);
	}

}