/* ========================================================================
 * Copyright 2014 macrosoft
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 macrosoft

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/

package co.edu.uniandes.csw.macrosoft.seccion.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.macrosoft.seccion.logic.dto.SeccionDTO;
import co.edu.uniandes.csw.macrosoft.seccion.logic.api.ISeccionLogicService;
import co.edu.uniandes.csw.macrosoft.seccion.master.logic.api._ISeccionMasterLogicService;
import co.edu.uniandes.csw.macrosoft.seccion.master.logic.dto.SeccionMasterDTO;
import co.edu.uniandes.csw.macrosoft.estudiante.logic.api.IEstudianteLogicService;
import co.edu.uniandes.csw.macrosoft.estudiante.logic.dto.EstudianteDTO;
import javax.inject.Inject;


public abstract class _SeccionMasterMockLogicService implements _ISeccionMasterLogicService {

    protected static ArrayList<SeccionMasterDTO> seccionMasterDtosList = new ArrayList<SeccionMasterDTO>() ;
    @Inject
    protected IEstudianteLogicService estudiantePersistance;
    @Inject
    protected ISeccionLogicService seccionPersistance;

    public SeccionMasterDTO createMasterSeccion(SeccionMasterDTO seccion) {

        seccionPersistance.createSeccion(seccion.getSeccionEntity());
        for (EstudianteDTO dto : seccion.getCreateenEspera_seccion()) {
            estudiantePersistance.createEstudiante(dto);
        }
        for (EstudianteDTO dto : seccion.getCreateinscritos_seccion()) {
            estudiantePersistance.createEstudiante(dto);
        }
        seccionMasterDtosList.add(seccion);
        return seccion;
    }

    public SeccionMasterDTO getMasterSeccion(Long id) {
        for (SeccionMasterDTO seccionMasterDTO : seccionMasterDtosList) {
            if (seccionMasterDTO.getSeccionEntity().getId() == id) {
                return seccionMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterSeccion(Long id) {
        for (SeccionMasterDTO seccionMasterDTO : seccionMasterDtosList) {
            if (seccionMasterDTO.getSeccionEntity().getId() == id) {

                for (EstudianteDTO dto : seccionMasterDTO.getCreateenEspera_seccion()) {
                    estudiantePersistance.deleteEstudiante(dto.getId());
                }
                seccionPersistance.deleteSeccion(seccionMasterDTO.getId());
                seccionMasterDtosList.remove(seccionMasterDTO);
                for (EstudianteDTO dto : seccionMasterDTO.getCreateinscritos_seccion()) {
                    estudiantePersistance.deleteEstudiante(dto.getId());
                }
                seccionPersistance.deleteSeccion(seccionMasterDTO.getId());
                seccionMasterDtosList.remove(seccionMasterDTO);
            }
        }

    }

    public void updateMasterSeccion(SeccionMasterDTO seccion) {

        // update Estudiante
        if (seccion.getUpdateenEspera_seccion() != null) {
            for (EstudianteDTO dto : seccion.getUpdateenEspera_seccion()) {
                estudiantePersistance.updateEstudiante(dto);
            }
        }
        // persist new Estudiante
        if (seccion.getCreateenEspera_seccion() != null) {
            for (EstudianteDTO dto : seccion.getCreateenEspera_seccion()) {
                EstudianteDTO persistedEstudianteDTO = estudiantePersistance.createEstudiante(dto);
                dto = persistedEstudianteDTO;
            }
        }
        // delete Estudiante
        if (seccion.getDeleteenEspera_seccion() != null) {
            for (EstudianteDTO dto : seccion.getDeleteenEspera_seccion()) {

                estudiantePersistance.deleteEstudiante(dto.getId());
            }
        }
        // update Estudiante
        if (seccion.getUpdateinscritos_seccion() != null) {
            for (EstudianteDTO dto : seccion.getUpdateinscritos_seccion()) {
                estudiantePersistance.updateEstudiante(dto);
            }
        }
        // persist new Estudiante
        if (seccion.getCreateinscritos_seccion() != null) {
            for (EstudianteDTO dto : seccion.getCreateinscritos_seccion()) {
                EstudianteDTO persistedEstudianteDTO = estudiantePersistance.createEstudiante(dto);
                dto = persistedEstudianteDTO;
            }
        }
        // delete Estudiante
        if (seccion.getDeleteinscritos_seccion() != null) {
            for (EstudianteDTO dto : seccion.getDeleteinscritos_seccion()) {

                estudiantePersistance.deleteEstudiante(dto.getId());
            }
        }
    }
}